version:  '3'
services:
  ServiceCenter:
    image: servicecomb/service-center
    ports:
      - 30101:30100
  Catalog:
    image: thanda/osi-catalogue
    ports:
      - 8089:8089 
    environment:
      CSE_REGISTRY_ADDR: http://ServiceCenter:30100
    links:
      - ServiceCenter
  Payment:
    image: thanda/osi-payment
    environment:
      SC_HOST: ServiceCenter
    links:
      - ServiceCenter
  MesherFrontend:
    image: thanda/mesher:osi
    environment:
      - CSE_REGISTRY_ADDR=http://ServiceCenter:30100
      - SERVICE_NAME=FrontEnd
      - VERSION=0.0.1
      - APP_ID=OSIConference
    ports:
      - 8088:80  
    links:
      - ServiceCenter
  Frontend:
    image: thanda/osi-frontend
    environment:
      - http_proxy=127.0.0.1:30101
    network_mode: "service:MesherFrontend"

